pipeline:
  build-uberjar:
    when:
      event: push
    image: registry.usw.co/uswitch/clojure
    secrets: [ "aws_access_key_id", "aws_secret_access_key"]
    commands:
      - lein deps
      - lein test
      - lein jar

  release:
    image: registry.usw.co/uswitch/clojure
    when:
      branch: master
      event: push
    secrets: [ "aws_access_key_id", "aws_secret_access_key"]
    commands:
      - lein deps
      - lein jar
      - lein deploy s3-releases
